[project]
name = "casa-arrow"
version = "0.1.0"
authors = [{ name = "Simon Perkins", email = "simon.perkins@gmail.com" }]
dependencies = ["pyarrow == 11.0.0"]
description = "C++ and Python Arrow Bindings for casacore"
readme = "README.rst"
requires-python = ">=3.8"
license = {text = "BSD-3-Clause"}

[build-system]
requires = ["setuptools", "setuptools-scm", "cython>=0.29.33,<0.30.0", "numpy>=1.24.1,<2.0.0", "pyarrow == 11.0.0"]
build-backend = "setuptools.build_meta"
