[tool.poetry]
name = "casa-arrow"
version = "0.1.0"
description = ""
build = "build.py"
authors = ["Simon Perkins <simon.perkins@gmail.com>"]
readme = "README.rst"
packages = [{include = "casa_arrow"}]

[tool.poetry.dependencies]
python = "^3.8"
pybind11 = "^2.10.3"
cython = "^0.29.33"
numpy = "^1.24.1"

[tool.poetry.group.dev.dependencies]
ipython = "^8.8.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core",
    "setuptools",
    "pyarrow >= 10.0.0",
    "pybind11 >=2.10.0",
    "cython >=0.29.0",
    "wheel"]
build-backend = "poetry.core.masonry.api"
